add kustomize and update tasks
Signed-off-by: Avi Biton <abiton@redhat.com>

diff --git a/managed/tkn-bundle/tkn-bundle.yaml b/managed/tkn-bundle/tkn-bundle.yaml
--- a/managed/tkn-bundle/tkn-bundle.yaml
+++ b/managed/tkn-bundle/tkn-bundle.yaml
@@ -2,7 +2,7 @@ apiVersion: tekton.dev/v1
 kind: Task
 metadata:
   labels:
-    app.kubernetes.io/version: "0.1"
+    app.kubernetes.io/version: "0.2"
     build.appstudio.redhat.com/build_type: "tkn-bundle"
   annotations:
     tekton.dev/pipelines.minVersion: "0.12.1"
@@ -128,50 +128,126 @@ spec:
       value: $(params.CONTEXT)
     - name: IMAGE
       value: $(params.IMAGE)
+    - name: URL
+      value: $(params.URL)
+    - name: REVISION
+      value: $(params.REVISION)
     script: |
-      #!/bin/env bash
+        #!/bin/env bash
 
-      set -o errexit
-      set -o pipefail
-      set -o nounset
+        set -o errexit
+        set -o pipefail
+        set -o nounset
+        set -ex
 
-      mapfile -t FILES < "${TASK_FILE}"
-      [[ ${#FILES[@]} -eq 0 ]] \
-        && echo "No YAML files matched by \"$CONTEXT\" in \"$(workspaces.source.path)/${SOURCE_CODE_DIR}\", aborting the build" \
-        && exit 1
-      exec 3>&1;
+        mapfile -t FILES <"${TASK_FILE}"
+        [[ ${#FILES[@]} -eq 0 ]] &&
+          echo "No YAML files matched by \"$CONTEXT\" in \"/var/workdir/${SOURCE_CODE_DIR}\", aborting the build" &&
+          exit 1
+        exec 3>&1
 
-      retry() {
+        retry() {
           local status
           local retry=0
           local -r interval=${RETRY_INTERVAL:-5}
           local -r max_retries=5
           while true; do
-              "$@" && break
-              status=$?
-              ((retry+=1))
-              if [ $retry -gt $max_retries ]; then
-                  return $status
-              fi
-              echo "info: Waiting for a while, then retry ..." 1>&2
-              sleep "$interval"
+            "$@" && break
+            status=$?
+            ((retry += 1))
+            if [ $retry -gt $max_retries ]; then
+              return $status
+            fi
+            echo "info: Waiting for a while, then retry ..." 1>&2
+            sleep "$interval"
           done
-      }
+        }
+        
+        function escape_tkn_bundle_arg() {
+          # the arguments to `tkn bundle --annotate` need to be escaped in a curious way
+          # see https://github.com/tektoncd/cli/issues/2402 for details
 
-      # shellcheck disable=SC2046
-      OUT="$(retry tkn bundle push "$IMAGE" \
-        $(printf ' -f %s' "${FILES[@]}") \
-        |tee /proc/self/fd/3)"
-      echo -n "$IMAGE" > "$(results.IMAGE_URL.path)"
-      digest="${OUT#*Pushed Tekton Bundle to *@}"
-      echo -n "${digest}" > "$(results.IMAGE_DIGEST.path)"
-      echo -n "${IMAGE}@${digest}" > "$(results.IMAGE_REF.path)"
+          local arg=$1
+          # replace single double-quotes with double double-quotes (this escapes the double-quotes)
+          local escaped_arg=${arg//\"/\"\"}
+          # wrap the whole thing in double-quotes (this escapes commas)
+          printf '"%s"' "$escaped_arg"
+        }
 
-      # cleanup task file
-      [[ -f "${TASK_FILE}" ]] && rm -f "${TASK_FILE}"
+        # Check if the task is kustomized
+        # A task considered to be kustomized when a kustomization file is found in the task dir
+        is_kustomized_task() {
+            local -r task_dir=$1
+            local -r kustomiztion_file="$task_dir/kustomization.yaml"
+            if [ -f "$kustomiztion_file" ] ; then
+                return 0
+            fi
+            return 1
+        }
+
+        # Generate a task from the kustomization file
+        generate_kustomized_task() {
+            local -r task_dir=$1
+            local -r prepared_task_file="$task_dir/generated-kustomized-task.yaml"
+            kubectl kustomize "$task_dir" >"$prepared_task_file"
+            echo "$prepared_task_file"
+        }
+        
+        task_dir=$(echo "${FILES[@]}" | awk -F'/' '{NF--; print $0}' OFS='/')
+
+        # If task is kustomized, generate it and replace the FILES value with the value of the generated task
+        # All other files will be ignored.
+        if is_kustomized_task "$task_dir"; then
+            echo "Generating a kustomized task from $task_dir/kustomization.yaml"
+            FILES=($(generate_kustomized_task "$task_dir"))
+        else
+            echo "Task is not Kustomized - continue"
+        fi
+
+        ANNOTATIONS=()
+        ANNOTATIONS+=("org.opencontainers.image.source=${URL}")
+        ANNOTATIONS+=("org.opencontainers.image.revision=${REVISION}")
+        ANNOTATIONS+=("org.opencontainers.image.url=${URL}/tree/${REVISION}/${CONTEXT}")
+
+        # Ensure an empty string is output rather than string "null" if the version label is not present
+        task_version=$(yq '.metadata.labels."app.kubernetes.io/version"' "${FILES[@]}" | sed '/null/d' | tr -d '[:space:]')
+        ANNOTATIONS+=("org.opencontainers.image.version=${task_version}")
+
+        
+        if [ -f "${task_dir}/README.md" ]; then
+          ANNOTATIONS+=("org.opencontainers.image.documentation=${URL}/tree/${REVISION}/${CONTEXT}/README.md")
+        fi
+
+        if [ -f "${task_dir}/TROUBLESHOOTING.md" ]; then
+          ANNOTATIONS+=("dev.tekton.docs.troubleshooting=${URL}/tree/${REVISION}/${CONTEXT}/TROUBLESHOOTING.md")
+        fi
+
+        if [ -f "${task_dir}/USAGE.md" ]; then
+          ANNOTATIONS+=("dev.tekton.docs.usage=${URL}/tree/${REVISION}/${CONTEXT}/USAGE.md")
+        fi
+        description=$(yq '.spec.description' "${FILES[@]}" | sed '/null/d' | tr -d '')
+        ANNOTATIONS+=("org.opencontainers.image.description=${description}")
+
+        echo "Added annotations:"
+        ANNOTATION_FLAGS=()
+        for annotation in "${ANNOTATIONS[@]}"; do
+          ANNOTATION_FLAGS+=("--annotate" "$(escape_tkn_bundle_arg "$annotation")")
+          echo "    - $annotation"
+        done
+
+        # shellcheck disable=SC2046
+        OUT="$(retry tkn bundle push "${ANNOTATION_FLAGS[@]}" "$IMAGE" \
+          $(printf ' -f %s' "${FILES[@]}") |
+          tee /proc/self/fd/3)"
+        echo -n "$IMAGE" >"$(results.IMAGE_URL.path)"
+        digest="${OUT#*Pushed Tekton Bundle to *@}"
+        echo -n "${digest}" >"$(results.IMAGE_DIGEST.path)"
+        echo -n "${IMAGE}@${digest}" >"$(results.IMAGE_REF.path)"
+
+        # cleanup task file
+        [[ -f "${TASK_FILE}" ]] && rm -f "${TASK_FILE}"
     securityContext:
       runAsUser: 0
     workingDir: $(workspaces.source.path)
   workspaces:
   - name: source
-  
